enum UserRole {
  STUDENT
  FACULTY
  ADMIN
}

type User {
  id: ID!
  name: String!
  email: String!
  department: String!
  role: UserRole!
  userEvents: [Event!]!
  onRegisteredEvents: [Event!]!
  answerRecords: [AnswerRecords!]
}

type VerifyResponse {
  isSuccess: Boolean!
  message: String!
  status: Int!
}

type Query {
  verifyUser: VerifyResponse!
}
